/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: DJMaesen (https://sketchfab.com/bumstrum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crate-3990cc9d604d4030a84b713db2ad4242
Title: Crate
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/crate/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh 
        geometry={nodes.crate_Crate_0.geometry} 
        material={materials.Crate} 
        rotation={[-Math.PI / 2, 0, 0]} 
        scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
