/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 robo.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/public/robo/robo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.obj1.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj10.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj11.geometry} material={nodes.obj11.material} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj12.geometry} material={nodes.obj12.material} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj13.geometry} material={nodes.obj13.material} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj14.geometry} material={nodes.obj14.material} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj15.geometry} material={nodes.obj15.material} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj16.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj2.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj3.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj4.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj5.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj6.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj7.geometry} material={materials['Material.006']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj8.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.obj9.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/robo.gltf')
